<?php
	/**
	 * Generated by Joomla Admin Generator
	 * An interface to implement for all controller
	 */

	interface Controller_Interface
	{
		/**
		 * Edit a record
		 *
		 * @param boolean
		 */
		public function editRecord($edit);
		
		/**
		 * Save a record
		 *
		 * @param array data
		 * @param string action
		 */
		public function saveRecord($data, $action = '');
		
		/**
		 * Show all records
		 */
		public function showRecord();
		
		/**
		 * Remove a record
		 */
		public function removeRecord();
	}
?>
