<?php

	/*
	** Generated by Joomla Admin Generator
	** Author: {AUTHOR_NAME}
	** Email: {AUTHOR_EMAIL}
	** 
	** Component:  {COMPONENT_PATH}
	** File: {FILE_NAME}
	** Time: {TIME}
	*/

	$c =& JRequest::getCmd('c','');
	$task =& JRequest::getCmd('task','show');
	$action =& JRequest::getCmd('action','');        

	include_once( JPATH_COMPONENT_ADMINISTRATOR.DS.'controllers'.DS."$c.php" );
	include_once( JPATH_COMPONENT_ADMINISTRATOR.DS.'models'.DS."models.php" );
	include_once(JPATH_COMPONENT_ADMINISTRATOR.DS."models".DS."helper.php");
	include_once( JPATH_COMPONENT_ADMINISTRATOR.DS.'views'.DS."admin.$c.html.php" );

	$cotroller_name = ucfirst($c)."Controller";
	$controller = new $cotroller_name();

	switch(strtolower($task))
	{
		case 'add':
			$controller->editRecord(false); break;
		case 'edit':
			$controller->editRecord(true); break;
		case 'remove':
		case 'removeRecord':
			$controller->removeRecord(); break;
		case 'apply':
		case 'save':
		case 'save2new':
		case 'save2copy':
			$controller->saveRecord( $_POST, $action, strtolower($task) ); break;
		default:
			$controller->showRecord(); break;
	}

?>
