<?php
	/*
	** Generated by Joomla Admin Generator
	** Author: {AUTHOR_NAME}
	** Email: {AUTHOR_EMAIL}
	** 
	** Component:  {COMPONENT_PATH}
	** File: {FILE_NAME}
	** Time: {TIME}
	*/
// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );

/**
 * Uninstall
 * @return unknown_type
 */
function com_uninstall()
{
	global $mainframe;
	$db =& JFactory::getDBO();
	$db_prefix = $mainframe->getCfg('dbprefix');
	$result = _runQueries($db);
	if(count($result)>=1)
	{
		foreach($result as $msg)
		{
			echo $msg."<br/>\n";
		}
	}else{
		echo "UnInstall Component Success";
	}
}

/**
 * Run sql queries
 * 
 * @param object $db
 * @return string msg
 */
function _runQueries($db)
{
	{DROPQUERIES}
	$msg = array();
	if( count($installQueries) >=1 )
	{
		foreach ( $installQueries as $query ) {
			$db->setQuery( $query );
			$db->query();
			if ( $db->getErrorNum() ) {
				$msg[] = '<br/>' . $db->stderr();
			}
		}
	}
	return $msg;
}

